name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Python libraries
      - name: Install gitpython
        run: python3 -m pip install gitpython

      # Install SLOC
      - name: Install SLOC
        run: sudo npm install sloc -g

      - name: Generate results.json
        run: python3 script.py

      - name: Prune results.json
        run: python3 prune.py
        
      # Commit back to the repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate results.json
          file_pattern: results.json
